name: flutterchallenges
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

flutter:

  uses-material-design: true
  assets:
    - assets/space_concept/
    - assets/travel_app/
    - assets/facebook_redesign/

  fonts:
    - family: Mark
      fonts:
        - asset: fonts/mark/Mark-Regular.otf
        - asset: fonts/mark/Mark-Bold.otf
          weight: 700
        - asset: fonts/mark/Mark-Medium.otf
          weight: 600
        - asset: fonts/mark/Mark-Light.otf
          weight: 500
        - asset: fonts/mark/Mark-Thin.otf
          weight: 400

    - family: SF-Pro-Display
      fonts:
        - asset: fonts/sf_pro_display/SF-Pro-Display-Regular.otf
        - asset: fonts/sf_pro_display/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: fonts/sf_pro_display/SF-Pro-Display-Semibold.otf
          weight: 700
        - asset: fonts/sf_pro_display/SF-Pro-Display-Medium.otf
          weight: 600
        - asset: fonts/sf_pro_display/SF-Pro-Display-Light.otf
          weight: 500

    - family: SF-Pro-Text
      fonts:
        - asset: fonts/sf_pro_text/SF-Pro-Text-Regular.otf
        - asset: fonts/sf_pro_text/SF-Pro-Text-Bold.otf
          weight: 800
        - asset: fonts/sf_pro_text/SF-Pro-Text-Semibold.otf
          weight: 700
        - asset: fonts/sf_pro_text/SF-Pro-Text-Medium.otf
          weight: 600
        - asset: fonts/sf_pro_text/SF-Pro-Text-Light.otf
          weight: 500

    - family: Hybi11-Amigo
      fonts:
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-Regular.ttf
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-Bold.ttf
          weight: 800
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-SemiBold.ttf
          weight: 700
        - asset: fonts/hybi11_amigo/Hybi11-Amigo-Light.ttf
          weight: 500
